<?php

declare(strict_types=1);

use Drupal\Core\Extension\ThemeHandlerInterface;
use Drupal\Core\Extension\ThemeInstallerInterface;
use Drupal\Core\Hook\Attribute\LegacyRequirementsHook;
use Drupal\canvas\AutoSave\AutoSaveManager;
use Drupal\canvas\CanvasNotificationHandler;

/**
 * Implements hook_module_preinstall().
 */
function canvas_module_preinstall(string $module): void {
  if ($module !== 'canvas') {
    return;
  }

  // Register the JSON schema definitions stream wrapper *prior* to installing
  // default config and hence prior to config validation. Otherwise validation
  // fails.
  // @see \Drupal\canvas\JsonSchemaDefinitionsStreamwrapper
  // @see \Drupal\Core\Extension\ModuleInstaller::install()
  // @todo Remove this after https://www.drupal.org/project/drupal/issues/3352063 lands.
  \Drupal::service('stream_wrapper_manager')->register();
}

/**
 * Implements hook_module_preuninstall().
 */
function canvas_module_preuninstall(string $module, bool $is_syncing): void {
  if ($module !== 'canvas') {
    return;
  }

  \Drupal::service(AutoSaveManager::class)->deleteAll();
}

/**
 * Implements hook_uninstall().
 */
function canvas_uninstall(bool $is_syncing): void {
  $schema = \Drupal::database()->schema();
  foreach ([CanvasNotificationHandler::NOTIFICATION_TABLE, CanvasNotificationHandler::NOTIFICATION_READ_TABLE] as $table) {
    if ($schema->tableExists($table)) {
      $schema->dropTable($table);
    }
  }
}

/**
 * Implements hook_requirements().
 *
 * @todo Remove when https://www.drupal.org/project/drupal/issues/3472008 is fixed in Drupal core.
 */
#[LegacyRequirementsHook]
function canvas_requirements(string $phase): array {
  $requirements = [];
  if ($phase === 'install' || $phase == 'runtime') {
    $canvas_stark_enabled = \Drupal::service('theme_handler')->themeExists('canvas_stark');
    if (!$canvas_stark_enabled) {
      $requirements['canvas_stark'] = [
        'title' => t('Drupal Canvas Theme'),
        'description' => t('The required theme <code>canvas_stark</code> is no longer installed due to manually modified changes to <code>core.extension</code>. The Drupal Canvas user interface will be broken without this theme. You can install it by running <code>drush theme:install canvas_stark</code>.'),
        'severity' => REQUIREMENT_WARNING,
      ];
    }

    // Check if JSON:API module is enabled.
    $json_api_enabled = \Drupal::moduleHandler()->moduleExists('jsonapi');
    if ($json_api_enabled) {
      $severity = REQUIREMENT_WARNING;
      // Check if PHP assertions are enabled and update the severity.
      // @see \Drupal\canvas\EventSubscriber\ApiMessageValidator::isProd()
      $assertions_disabled = TRUE;
      // @phpstan-ignore-next-line booleanNot.alwaysTrue
      assert(!($assertions_disabled = FALSE));
      // @phpstan-ignore-next-line booleanNot.alwaysTrue function.alreadyNarrowedType
      if (!$assertions_disabled) {
        $severity = REQUIREMENT_ERROR;
      }
      $requirements['canvas'] = [
        'title' => t('Drupal Canvas'),
        'description' => t("Drupal Canvas requires the <code>justinrainbow/json-schema</code> library which may impact site performance when the JSON:API module is installed and PHP assertions are enabled. See <a href=':url'>:url</a> for more information.", [':url' => 'https://www.drupal.org/project/drupal/issues/3472008']),
        'severity' => $severity,
      ];
    }
  }
  return $requirements;
}

/**
 * Install `canvas_stark` theme if not enabled.
 */
function canvas_update_11200(): void {
  /** @var \Drupal\Core\Extension\ThemeHandlerInterface $theme_handler */
  $theme_handler = \Drupal::service(ThemeHandlerInterface::class);
  if (!$theme_handler->themeExists('canvas_stark')) {
    // Ensure canvas_stark is installed.
    // For that to happen when installing canvas with a recipe, we cannot do it
    // conditionally based on the `$is_syncing` flag.
    // @see \Drupal\canvas\Theme\CanvasThemeNegotiator
    // @see \Drupal\Core\Theme\ThemeNegotiator::determineActiveTheme()
    \Drupal::service(ThemeInstallerInterface::class)->install(['canvas_stark']);

    // No need to manually flush caches during the update.
    // @see \Drupal\system\Controller\DbUpdateController::triggerBatch()
  }
}
